# Generated by Django 4.1.7 on 2023-03-06 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wisata',
            fields=[
                ('id_tempat', models.AutoField(primary_key=True, serialize=False)),
                ('nama_tempat', models.CharField(max_length=200)),
                ('latitude', models.FloatField(max_length=200)),
                ('longitude', models.FloatField(max_length=200)),
                ('lokasi', models.CharField(max_length=200)),
                ('keterangan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Galeri',
            fields=[
                ('id_galeri', models.AutoField(primary_key=True, serialize=False)),
                ('nama_galeri', models.CharField(max_length=250)),
                ('gambar', models.ImageField(null=True, upload_to='dashboard/image_upload')),
                ('keterangan', models.TextField()),
                ('wisata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.wisata')),
            ],
        ),
    ]
