# Generated by Django 4.1.7 on 2023-03-06 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galeri',
            options={'verbose_name_plural': 'Galeri'},
        ),
        migrations.AlterModelOptions(
            name='wisata',
            options={'verbose_name_plural': 'Wisata'},
        ),
    ]
