# Generated by Django 4.1.7 on 2023-03-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_galeri_options_alter_wisata_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wisata',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
