# Generated by Django 4.1.7 on 2023-05-03 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_wisata_keterangan'),
    ]

    operations = [
        migrations.AddField(
            model_name='wisata',
            name='jenis',
            field=models.CharField(blank=True, choices=[('Wisata', 'Wisata'), ('Kuliner', 'Kuliner')], max_length=256, null=True),
        ),
    ]
